### ISSUE TITLE
RSS/Atom Feed

### ISSUE THREAD

**Issue by pointlessone** [0xadada/0xadada.github.io#22]
A feed would let people read your articles from the comfort of their cosy feed reader. Also would let them know when there a new one.

**Comment by 0xadada** [comment]
@pointlessone Its a good idea, but do many people use feed readers anymore? Most of them are either dead or subscription-based apps. its probably not worth the time.

**Comment by pointlessone** [comment]
I can't tell how many people use feed readers. I do. And I'm sure as heck missing your content because I'm not going to manually visit your blog. Not your in particular, just any blog. I just don't have that kind of time and memory. If there's no feed then I'm just not getting the updates.

**Comment by 0xadada** [comment]
> I can't tell how many people use feed readers. I do. And I'm sure as heck missing your content because I'm not going to manually visit your blog. Not your in particular, just any blog. I just don't have that kind of time and memory. If there's no feed then I'm just not getting the updates.

@pointlessone i agree. I'll keep this ticket open and see what it takes to add the feed 👍

**Comment by ipfans** [comment]
+1 for RSS feed

**Comment by 0xadada** [comment]
@pointlessone @ipfans i've opened https://github.com/0xadada/0xadada.pub/pull/30 please review

**Comment by 0xadada** [comment]
@pointlessone @ipfans the RSS feed is now at https://0xadada.pub/rss.xml

thanks for the suggestion 👍
